---

- name: Setup Docker
  hosts: localhost
  become_user: root
  gather_facts: true
  tasks:

  - name: Install prerequisites
    become: true
    apt:
     name: "{{ item }}"
     update_cache: yes
     state: present
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

  - name: Add Docker GPG key
    become: true
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"

  - name: Add Docker APT repository
    become: true
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge

  - name: Install Docker
    become: true
    apt:
      name: "docker-ce"
      state: present
      update_cache: yes
